Repository chanzuckerberg/single-cell-data-portal, pull requests merged in 2020-08, with the labels that each got.

#484 Implementing DbUtils as a singleton
  backend/corpora/common/utils/db_utils.py
  backend/corpora/lambdas/api/v1/project.py
  backend/corpora/lambdas/api/v1/submission.py
Labels: bot/merge

#511 332 cookie banner
  frontend/.env.development
  frontend/src/common/constants/localStorageKeys.ts
  frontend/src/common/localStorage/get.ts
  frontend/src/common/localStorage/set.ts
  frontend/src/components/CookieBanner/index.tsx
  frontend/src/components/CookieBanner/style.ts
  frontend/src/pages/index.tsx
Labels: bot/merge

#521 add guard clause for window object since SSR
  frontend/src/common/localStorage/get.ts
  frontend/src/common/localStorage/set.ts
Labels: bot/merge

#533 496-DP-serve-static-assets
  frontend/gatsby-config.js
  frontend/package-lock.json
  frontend/package.json
Labels: bot/merge

#544 ci: automatically deploy prod using github actions
  .github/workflows/deploy-prod.yml
Labels: Infra, bot/merge

#538 Thuang 529 dropdown to direct link
  frontend/src/common/entities.ts
  frontend/src/common/fixtures/projects.ts
  frontend/src/components/ProjectList/components/Dataset/components/ViewDataset/index.tsx
  frontend/src/components/ProjectList/components/Dataset/components/ViewDataset/style.ts
  frontend/src/components/ProjectList/components/Dataset/components/ViewDatasetAssets/DatasetAsset.tsx
  frontend/src/components/ProjectList/components/Dataset/components/ViewDatasetAssets/index.tsx
  frontend/src/components/ProjectList/components/Dataset/index.tsx
  frontend/src/components/ProjectList/components/Heading/index.tsx
  frontend/src/components/ProjectList/components/Heading/style.ts
  frontend/src/pages/index.tsx
Labels: bot/merge, frontend

#541 ci: fix staging auto deploy
  backend/chalice/api_server/Makefile
Labels: bot/merge

#548 update-FE-deployment-url
  backend/config/corpora-api.yml
  frontend/src/common/entities.ts
  frontend/src/common/fixtures/projects.ts
  frontend/src/components/ProjectList/components/Dataset/components/ViewDataset/index.tsx
Labels: bot/merge

#552 update-logo
  frontend/gatsby-config.js
  frontend/src/common/images/logo.svg
  frontend/src/components/common/Logo/index.tsx
  frontend/src/components/common/Logo/style.ts
  frontend/src/images/logo-hca-white@2x.png
  frontend/src/images/logo-hca.png
  frontend/src/svg.d.ts
Labels: bot/merge

#553 update-site-description
  frontend/gatsby-config.js
Labels: bot/merge
